import type { CreateAccountPayload } from "./types";

// ─── Default chart of accounts ────────────────────────────────────────────────
// Seeded on first run for a new tenant. Mirrors Auction Flex 360 defaults.

export const DEFAULT_ACCOUNTS: Omit<CreateAccountPayload, "tenant_id">[] = [
  // Parent: Money In or Out
  {
    parent_account_id: null,
    number: 1010,
    description: "Money In or Out",
    accepts_receipts: true,
    accepts_payments: true,
    surcharge_pct: 0,
    surcharge_flat: 0,
    surcharge_target: "buyer",
    rounding: "none",
    is_active: true,
  },
  {
    parent_account_id: 1010,
    number: 1012,
    description: "Cash",
    accepts_receipts: true,
    accepts_payments: true,
    surcharge_pct: 0,
    surcharge_flat: 0,
    surcharge_target: "buyer",
    rounding: "nickel",
    is_active: true,
  },
  {
    parent_account_id: 1010,
    number: 1020,
    description: "Visa",
    accepts_receipts: true,
    accepts_payments: false,
    surcharge_pct: 0,
    surcharge_flat: 0,
    surcharge_target: "buyer",
    rounding: "none",
    is_active: true,
  },
  {
    parent_account_id: 1010,
    number: 1021,
    description: "MasterCard",
    accepts_receipts: true,
    accepts_payments: false,
    surcharge_pct: 0,
    surcharge_flat: 0,
    surcharge_target: "buyer",
    rounding: "none",
    is_active: true,
  },
  {
    parent_account_id: 1010,
    number: 1022,
    description: "American Express",
    accepts_receipts: true,
    accepts_payments: false,
    surcharge_pct: 0,
    surcharge_flat: 0,
    surcharge_target: "buyer",
    rounding: "none",
    is_active: true,
  },
  {
    parent_account_id: 1010,
    number: 1023,
    description: "Discover",
    accepts_receipts: true,
    accepts_payments: false,
    surcharge_pct: 0,
    surcharge_flat: 0,
    surcharge_target: "buyer",
    rounding: "none",
    is_active: true,
  },
  {
    parent_account_id: 1010,
    number: 1030,
    description: "Stripe",
    accepts_receipts: true,
    accepts_payments: false,
    surcharge_pct: 0,
    surcharge_flat: 0,
    surcharge_target: "buyer",
    rounding: "none",
    is_active: true,
  },
  {
    parent_account_id: 1010,
    number: 1031,
    description: "Stripe ACH",
    accepts_receipts: true,
    accepts_payments: false,
    surcharge_pct: 0,
    surcharge_flat: 0,
    surcharge_target: "buyer",
    rounding: "none",
    is_active: true,
  },
  {
    parent_account_id: 1010,
    number: 1040,
    description: "Check",
    accepts_receipts: true,
    accepts_payments: false,
    surcharge_pct: 0,
    surcharge_flat: 0,
    surcharge_target: "buyer",
    rounding: "none",
    is_active: true,
  },
  // Parent: Buyer Auction Charges
  {
    parent_account_id: null,
    number: 4200,
    description: "Buyer Auction Charges",
    accepts_receipts: false,
    accepts_payments: false,
    surcharge_pct: 0,
    surcharge_flat: 0,
    surcharge_target: "buyer",
    rounding: "none",
    is_active: true,
  },
  {
    parent_account_id: 4200,
    number: 4201,
    description: "Miscellaneous Charge",
    accepts_receipts: false,
    accepts_payments: false,
    surcharge_pct: 0,
    surcharge_flat: 0,
    surcharge_target: "buyer",
    rounding: "none",
    is_active: true,
  },
  {
    parent_account_id: 4200,
    number: 4202,
    description: "Shipping & Handling",
    accepts_receipts: false,
    accepts_payments: false,
    surcharge_pct: 0,
    surcharge_flat: 0,
    surcharge_target: "buyer",
    rounding: "none",
    is_active: true,
  },
];

// ─── Default roles + permission matrix ───────────────────────────────────────

import type { Permission, UserRole } from "./types";

export const ROLE_PERMISSIONS: Record<Exclude<UserRole, "custom">, Permission> = {
  owner: {
    edit_miscellaneous: true,
    create_edit_auctions: true,
    run_live_auction: true,
    process_payments: true,
    view_reports: true,
    export_financials: true,
    manage_users: true,
    transfer_ownership: true,
    manage_billing: true,
  },
  admin: {
    edit_miscellaneous: true,
    create_edit_auctions: true,
    run_live_auction: true,
    process_payments: true,
    view_reports: true,
    export_financials: true,
    manage_users: true,
    transfer_ownership: false,
    manage_billing: false,
  },
  clerk: {
    edit_miscellaneous: false,
    create_edit_auctions: false,
    run_live_auction: true,
    process_payments: true,
    view_reports: true,
    export_financials: false,
    manage_users: false,
    transfer_ownership: false,
    manage_billing: false,
  },
  cataloger: {
    edit_miscellaneous: false,
    create_edit_auctions: true,
    run_live_auction: false,
    process_payments: false,
    view_reports: true,
    export_financials: false,
    manage_users: false,
    transfer_ownership: false,
    manage_billing: false,
  },
  accountant: {
    edit_miscellaneous: false,
    create_edit_auctions: false,
    run_live_auction: false,
    process_payments: false,
    view_reports: true,
    export_financials: true,
    manage_users: false,
    transfer_ownership: false,
    manage_billing: false,
  },
};

export const ROLE_DESCRIPTIONS: Record<Exclude<UserRole, "custom">, string> = {
  owner: "Full access. Single user. Cannot be deleted or transferred without explicit ownership transfer.",
  admin: "Full access except billing and ownership transfer.",
  clerk: "Runs live auctions and processes payments. Cannot edit settings or create auctions.",
  cataloger: "Creates and edits lots and auctions. Cannot run auctions or process payments.",
  accountant: "Read-only on operations. Full access to reports and financial exports.",
};

// ─── Company defaults ─────────────────────────────────────────────────────────

export const DEFAULT_COMPANY_SETTINGS = {
  default_permission_cap: 9_999_999.99,
  default_registration_mode: "verification" as const,
  card_tester_threshold: 10,
  lockout_window_hours: 24,
  timezone: "America/New_York",
};
